#!/bin/bash
quotes=(
    "I do bite my thumb, sir"
    "Would thou wert clean enough to spit upon!"
    "I do desire we may be strangers"
    "Thou whoreson zed, thou unnecessary letter!"
    "You Banbury cheese!"
    "I am sick when I do look on thee"
    "I do desire we may be better strangers"
    "There’s no more faith in thee than in a stewed prune"
    "To be, or not to be, that is the question"
    "All the world's a stage"
    "And all the men and women merely players"
    "The web of our life is of a mingled yarn, good and ill together"
    "I love long life better than figs"
    "This tiger-footed rage"
    "Come not between the dragon and his wrath!"
    "I understand a fury in your words"
    "But not the words"
    "Who is man that is not angry"
    "Heat not a furnace for your foe so hot"
    "That it do singe yourself"
    "Convert to anger"
    "Blunt not the heart"
    "Enrage it"
    "There is no following her in this fierce vein"
    "I would my father look'd but with my eyes."
    "It is a wise father that knows his own child"
    "Who would be a father!"
    "It is a wise father that knows his own child."
    "The course of true love never did run smooth"
    "If music be the food of love, play on"
    "Speak low, if you speak love"
    "The sight of lovers feedeth those in love"
    "Get thee a good husband, and use him as he uses thee"
    "Time goes on crutches till love hath all his rites"
    "But where there is true friendship, there needs none"
    "That which I would discover"
    "The law of friendship bids me to conceal"
    "Thy friendship makes us fresh"
    "There is flattery in friendship"
    "Most friendship is feigning"
    "Most loving is folly"
    "To me, fair friend, you never can be old"
    "One touch of nature makes the whole world kin"
    "For, being green, there is great hope"
    "And thorough this distemperature we see"
    "The seasons alter"
    "All things are ready if our minds be so"
    "Nature craves"
    "All dues be rendered to their owners"
    "Our remedies oft in ourselves do lie"
    "Which we ascribe to heaven"
    "O, I have ta'en"
    "Too little care of this"
    "The skies look grimly"
    "And threaten present blusters"
    "Let me be that I am"
    "And seek not to alter me"
    "What’s past is prologue"
    "We know what we are"
    "I had rather hear my dog bark at a crow than a man swear he loves me"
    "This above all - to thine own self be true"
    "We are such stuff as dreams are made on"
    "Were kisses all the joys in bed"
    "One woman would another wed."
)


input="$1"
bin=$(echo -n "$input" | xxd -b -c1 | awk '{print $2}' | tr -d '\n')
pad=$(( (6 - ${#bin}%6)%6 ))
bin=$(printf "%s%0*d" "$bin" "$pad" 0)

output=""
for ((i=0; i<${#bin}; i+=6)); do
  chunk=${bin:i:6}
  dec=$((2#$chunk))
  output+="${quotes[$dec]}"
done

echo "$output"
